sudo-project/sudo

logsrvd/logsrvd.c
Patch is applied to solve the issue when a certificate file contains not just the one certificate, but the whole chain of trust.
=> Proper handling of certificate chain file

doc/sudo.conf.man.in, doc/sudo.conf.mdoc.in, doc/sudo_plugin_python.man.in, doc/sudo_plugin_python.mdoc.in, plugins/python/Makefile.in, plugins/sudoers/sudoers_debug.c
Some little fixes related to the python plugin support.
- python plugin examples install path
- a debug subsystem deregistration warning
- a little doc
=> Python plugins little fixes

logsrvd/sendlog.c
fixes a compilation error when sudo is configured without --enable-openssl
=> fixed compiler error when sudo is configured without --enable-openssl

MANIFEST, plugins/python/Makefile.in, plugins/python/example_approval_plugin.py, plugins/python/python_plugin_approval.c, plugins/python/python_plugin_approval_multi.inc, plugins/python/python_plugin_audit.c, plugins/python/python_plugin_common.c, plugins/python/python_plugin_common.h, plugins/python/python_plugin_io.c, plugins/python/python_plugin_policy.c, plugins/python/regress/check_python_examples.c, plugins/python/regress/plugin_approval_test.py, plugins/python/regress/testdata/check_multiple_approval_plugin_and_arguments.stderr, plugins/python/regress/testdata/check_multiple_approval_plugin_and_arguments.stdout, plugins/python/regress/testhelpers.c, plugins/python/regress/testhelpers.h, plugins/python/sudo_python_module.c, plugins/python/sudo_python_module.h
Approval plugins can be written in python. An example plugin gets shipped.
=> Python approval plugin wrapper

plugins/python/python_plugin_approval.c, plugins/python/python_plugin_common.c, plugins/python/python_plugin_common.h, plugins/python/regress/testhelpers.c, plugins/python/sudo_python_module.c
Some little fixes to python part.
=> Python little fixes

lib/iolog/iolog_fileio.c, logsrvd/eventlog.c, logsrvd/iolog_writer.c
A little fix I bumped into with logsrvd.
=> Logsrvd fixes

logsrvd/logsrvd.c
=> add missing shudown of TLS connection

src/sudo_edit.c
In selinux_edit_copy_tfiles() when there is only one file and the open()
fails then number of arguments is lower than expected.
Sudo should return error with or without "Defaults !sudoedit_checkdir" set.
This was found with regression testing of CVE-2021-23240.
Signed-off-by: Radovan Sroka <rsroka@redhat.com>
=> Fixed bad condition for sesh args

examples/sudoers
`sudoers.in` was changed by 1d13533
=> Sync example sudoers with default sudoers

docs/sudoers.man.in, docs/sudoers.mdoc.in
Minor typo; discovered accidentally while writing https://github.com/sudo-project/sudo/issues/153
=> Add missing colon in Tag_Spec documentation

docs/sudoers.man.in, docs/sudoers.mdoc.in
Closes https://github.com/sudo-project/sudo/issues/153 with documentation as proposed on https://github.com/sudo-project/sudo/pull/155#issuecomment-1148758900
=> Improve Tag_Spec EBNF documentation

plugins/sudoers/cvtsudoers.c, src/sudo_intercept_common.c
Delete extra semicolons.
Signed-off-by: Li kunyu <kunyu@nfschina.com>
=> sudoers/cvtsudoers: Remove the repeated ';' from code

lib/util/rcstr.c
=> sudo_rcstr_dup: Fix potential NULL pointer deref

plugins/sudoers/visudo.c
=> check_syntax(): Remove duplicate calls to init_defaults()

lib/util/Makefile.in
There is a wrong command in the lib/util/Makefile.in file.
=> fix command error for lib/util/Makefile.in

lib/util/lbuf.c
Some of translations use "%n$s" format to relocate strings, and sudo_lbuf_append_v1 do not support it now, so I just add the support for it.
Related translations I found in `plugins/sudoers/po/zh_CN.po:3020` is pasted here.
```
#: plugins/sudoers/parse.c:876
#, c-format
msgid "Matching Defaults entries for %s on %s:\n"
msgstr "匹配 %2$s 上 %1$s 的默认条目：\n"
```
=> Add %n$s support for sudo_lbuf_append_v1

lib/util/mktemp.c, lib/util/regress/tailq/hltq_test.c, lib/util/sudo_debug.c, lib/util/ttyname_dev.c, plugins/group_file/plugin_test.c, plugins/sudoers/editor.c, plugins/sudoers/filedigest.c, plugins/sudoers/match_addr.c, plugins/sudoers/match_digest.c, plugins/sudoers/regress/env_match/check_env_pattern.c, plugins/sudoers/regress/exptilde/check_exptilde.c, plugins/sudoers/sudoreplay.c, plugins/sudoers/testsudoers.c, plugins/sudoers/tsdump.c, plugins/sudoers/visudo.c, src/exec_monitor.c, src/limits.c, src/sesh.c, src/sudo.c, src/sudo.h, src/sudo_edit.c
This saves instructions that are related to casting as well as compiler warnings. This is the last PR of this type I plan to make.
=> Avoid compiler casting warnings Part 2

lib/eventlog/eventlog.c, lib/eventlog/regress/eventlog_store/store_json_test.c, lib/eventlog/regress/eventlog_store/store_sudo_test.c, lib/eventlog/regress/logwrap/check_wrap.c, lib/eventlog/regress/parse_json/check_parse_json.c, lib/iolog/regress/iolog_path/check_iolog_path.c, lib/util/regress/hexchar/hexchar_test.c, lib/util/regress/strsplit/strsplit_test.c, lib/util/regress/sudo_conf/conf_test.c, logsrvd/logsrvd.c, logsrvd/regress/logsrvd_conf/logsrvd_conf_test.c, logsrvd/sendlog.c, plugins/group_file/plugin_test.c, plugins/sudoers/cvtsudoers.c, plugins/sudoers/regress/check_symbols/check_symbols.c, plugins/sudoers/regress/iolog_plugin/check_iolog_plugin.c, plugins/sudoers/regress/parser/check_addr.c, plugins/sudoers/testsudoers.c, plugins/sudoers/visudo.c, src/exec_monitor.c, src/exec_nopty.c, src/exec_pty.c, src/sesh.c, src/sudo.c
We also put NOTREACHED where it applies.
=> Mark functions not returning as sudo_noreturn

plugins/sudoers/gram.c, plugins/sudoers/gram.y, plugins/sudoers/timestamp.c, plugins/sudoers/tsgetgrpw.c, src/sudo.c
This should be the last of them.
=> Fixed even more signedness and conversion issues

lib/util/roundup.c
Said comment no longer applies.
=> Remove comment about algorithm being from bit-twiddling hacks

lib/util/roundup.c
No need to call sudo_pow2_roundup_v2.
=> Optimize sudo_pow2_roundup_v1

lib/eventlog/regress/logwrap/check_wrap.c, lib/util/glob.c, lib/util/mksiglist.c, lib/util/mksigname.c, lib/util/regress/glob/globtest.c, lib/util/regress/parse_gids/parse_gids_test.c, logsrvd/sendlog.c, plugins/group_file/plugin_test.c, plugins/python/regress/check_python_examples.c, plugins/sudoers/getdate.c, plugins/sudoers/getdate.y, plugins/sudoers/sudoreplay.c, plugins/sudoers/tsdump.c
fprintf does extra work and meant for formatting strings.
=> Prefer fputs over fprintf where possible

plugins/sudoers/sudoers_hooks.c
def_sudoers_locale is already a char*
=> Redundant cast removal

INSTALL.md, docs/UPGRADE.md, lib/util/event.c, lib/util/fatal.c, lib/util/fnmatch.c, lib/util/lbuf.c, lib/util/snprintf.c, lib/util/sudo_dso.c, plugins/python/example_io_plugin.py, plugins/python/example_policy_plugin.py, plugins/sample/sample_plugin.c, plugins/sudoers/auth/fwtk.c, plugins/sudoers/def_data.c, plugins/sudoers/def_data.in, plugins/sudoers/ldap.c, plugins/sudoers/lookup.c, plugins/sudoers/parse.h, plugins/sudoers/parse_ldif.c, plugins/sudoers/policy.c, plugins/sudoers/pwutil.h, plugins/sudoers/set_perms.c, plugins/sudoers/sssd.c, plugins/sudoers/sudoers.c, src/exec.c, src/exec_monitor.c, src/exec_ptrace.c, src/exec_pty.c
Eradicated typographical and grammatical imperfections from the repository.
=> Typographical and Grammatical Fixes

plugins/sudoers/iolog_path_escapes.c
It's just strlcpy except it replaces '/' with '_'.
=> Add restrict qualifiers to strlcpy_no_slash

include/sudo_util.h, lib/util/uuid.c
=> sudo_uuid_to_string_v1's first argument should be const

include/sudo_util.h, lib/util/uuid.c
Assembler difference: https://godbolt.org/z/crav7dofv
=> Use restrict to optimize sudo_uuid_to_string_v1

include/sudo_util.h, lib/util/multiarch.c
stat is restrict-qualified, so shouldstat_multiarch
=> Restrict-qualify stat_multiarch

include/compat/glob.h, lib/util/glob.c
glob is restrict-qualified in the standard
=> Restrict-qualify glob and its functions

NEWS
=> docs: update NEWS
