- configure
- examples/sudo_logsrvd.conf
- logsrvd/Makefile.in
- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
- logsrvd/logsrvd_conf.c
- logsrvd/sendlog.c
This PR implements TLS layer for Sudo Audit Server using OpenSSL. The utility 'sudo_sendlog' has been updated as well to be able to communicate with the audit server over TLS.
> Audit server tls support

- include/log_server.pb-c.h
- lib/logsrv/log_server.pb-c.c
- lib/logsrv/log_server.proto
- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
- logsrvd/logsrvd_conf.c
- logsrvd/sendlog.c
- logsrvd/sendlog.h
Modifications
- Two new fields (tls, tls_checkpeer) have been added to the ServerHello message in log_sever.proto 
- ServerHello message is unencrypted now in every case and contains the tls and tls_checkpeer fields
- TLS communication has been refactored to do everything asynchronous
- Audit server now operates with event timeout instead of socket timeout
Known issues:
- if sudo is compiled WITHOUT --enable-openssl, but sudo_logsrvd.conf contains config options for tls, logsrvd throws Segmentation Fault at startup (unknown key)
> Sudo audit Server - TLS protocol update

- logsrvd/logsrvd.c
- logsrvd/logsrvd_conf.c
This PR fixes issues when various cert and key paths are not set in sudo_logsrvd.conf.
- CA cert and server cert path default values are the same as in examples/sudo_logsrvd.conf.
- If private key file is not set in the config, the audit server tries to load it from the cert file.
> Audit Server - add default values for cert paths

- MANIFEST
- include/hostcheck.h
- lib/iolog/Makefile.in
- lib/iolog/hostcheck.c
- logsrvd/Makefile.in
- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
- plugins/sudoers/Makefile.in
- plugins/sudoers/iolog.c
- plugins/sudoers/iolog_client.c
- plugins/sudoers/iolog_plugin.h
This PR implements hostname/IP validation in SSL certificates.
- On client side, the server certificate's SAN field (GEN_DNS, GEN_IPADD) or CN field is compared to the server's name/address
- On server side, if tls_checkpeer option is set in sudo_logsrvd.conf, the client's certificate's SAN/CN field is compared to the client's IP address. If the client cert contains a name, the validation process checks that the name resolves to the client's IP address or not.
> Client/Server Identity validation for the audit server

- examples/sudo_logsrvd.conf
- include/log_server.pb-c.h
- lib/logsrv/log_server.pb-c.c
- lib/logsrv/log_server.proto
- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
- logsrvd/logsrvd_conf.c
- logsrvd/sendlog.c
- plugins/sudoers/iolog_client.c
This PR handles the use case when CA certs are note distributed to clients to authenticate the server.
A new configuration option (tls_verify) has been added to sudo_logsrvd.conf.
If tls_verify is set:
- Server performs a certificate verification on its own certificate at startup
- Client will perform server authentication (verify server's cert) during tls handshake.
If tls_verify is not set
- Server skips the verification of its own certificate
- Client won't authenticate the server, therefore no need to set ca_bundle file in /etc/sudoers
The tls_checkpeer configuration option is independent from tls_verify. If both set to false, tls_cacert option is not required to set in sudo_logsrvd.conf, since both server authentication and client authentication are turned off.
> Optional server cert check

- plugins/python/pyhelpers.c
- plugins/python/pyhelpers.h
- plugins/python/python_plugin_common.c
- plugins/python/python_plugin_common.h
- plugins/python/python_plugin_group.c
- plugins/python/python_plugin_io.c
- plugins/python/python_plugin_policy.c
- plugins/python/regress/check_python_examples.c
- plugins/python/regress/plugin_conflict.py
- plugins/python/regress/testdata/check_python_plugins_do_not_affect_each_other.stdout
If they are run in the same interpreter, they can affect each other's state.
> Make each python plugin run in separate interpreters

- plugins/python/sudo_python_module.c
PyArg_ParseTuple sets the py_config_tuple pointer, but it does not
increment the reference count, so by decrementing, we end up freeing
the argument passed in.
> plugins/sudo_python_module: Fix double free in sudo.options_as_dict function

- logsrvd/sendlog.c
- logsrvd/sendlog.h
sudo_sendlog has been refactored in order to be able to send one I/O log multiple times in parallel (for testing purposes)
> Refactor sudo_sendlog 

- Makefile.in
The scriptdir contained a path relative to where the target was started.
The scripts are called like "$scriptdir/script_name" which is fine with
relative path as well, until the current directory is not changed.
But things like
cd $srcdir && $scriptdir/script_name
fails (if building in separate build directory).
> Makefile.in: fix install target for out of source build

- plugins/python/pyhelpers.c
- plugins/python/pyhelpers.h
- plugins/python/python_plugin_common.c
- plugins/python/regress/check_python_examples.c
- plugins/python/regress/testdata/check_example_debugging_load@diag.log
- plugins/python/regress/testhelpers.c
- plugins/python/sudo_python_debug.c
- plugins/python/sudo_python_module.c
We only deinit the python interpreters when sudo unlinks our plugin so we can avoid issues with python modules which do not support the interpreter reload use case (eg. datetime.strptime).
Also restores python inittab, so the "sudo" module entry (with the module's init function) can not remain there as garbage (noticed this as a test crash on OpenBSD).
> No python interpreter deinit

- doc/sudo_plugin_python.man.in
- doc/sudo_plugin_python.mdoc.in
- plugins/python/python_plugin_approval.c
- plugins/python/python_plugin_audit.c
- plugins/python/python_plugin_common.c
- plugins/python/python_plugin_common.h
- plugins/python/python_plugin_io.c
- plugins/python/python_plugin_policy.c
- plugins/python/regress/check_python_examples.c
- plugins/python/regress/testdata/check_example_audit_plugin_version_display.stdout
- plugins/python/regress/testdata/check_example_debugging_py_calls@info.log
- plugins/python/regress/testdata/check_example_io_plugin_version_display_full.stdout
- plugins/python/regress/testdata/check_example_policy_plugin_version_display_full.stdout
- plugins/python/regress/testdata/check_multiple_approval_plugin_and_arguments.stdout
Show version now displays the class and the path of the python plugin.
Also fixes the crash of "sudo -V" if a python approval plugin did not have a show_version function.
> Python display version improve

- MANIFEST
- doc/sudo_plugin_python.man.in
- doc/sudo_plugin_python.mdoc.in
- plugins/python/Makefile.in
- plugins/python/example_debugging.py
- plugins/python/python_baseplugin.c
- plugins/python/python_convmessage.c
- plugins/python/python_importblocker.c
- plugins/python/python_loghandler.c
- plugins/python/python_plugin_common.c
- plugins/python/regress/check_python_examples.c
- plugins/python/regress/testdata/check_example_debugging_c_calls@diag.log
- plugins/python/regress/testdata/check_example_debugging_c_calls@info.log
- plugins/python/regress/testdata/check_example_debugging_plugin@err.log
- plugins/python/regress/testdata/check_example_debugging_plugin@info.log
- plugins/python/regress/testdata/check_loading_fails_missing_classname.stderr
- plugins/python/regress/testdata/check_loading_succeeds_with_missing_classname.stdout
- plugins/python/sudo_python_module.c
- plugins/python/sudo_python_module.h
Some improvements to make writing/using python plugins easier:
- "ClassName" became optional and "ModulePath" can be relative as well, so you do not have to write such long line to register a python plugin. Also the possible "ClassName"s will be printed out in the error message to make it easier to choose.
- Python default "logging" module can also be used to utilize the sudo debug subsystem. My intention with this is that the python modules the plugin uses can have their logging as well, so it is a common thing that most plugins would need to affect. Redirecting to sudo debug system makes a default which can commonly be good enough.
> Python make things easier

- doc/sudo_logsrv.proto.man.in
- doc/sudo_logsrv.proto.mdoc.in
- doc/sudo_logsrvd.conf.man.in
- doc/sudo_logsrvd.conf.mdoc.in
- doc/sudo_sendlog.man.in
- doc/sudo_sendlog.mdoc.in
- doc/sudoers.man.in
- doc/sudoers.mdoc.in
- examples/sudo_logsrvd.conf
- include/log_server.pb-c.h
- include/sudo_util.h
- lib/logsrv/log_server.pb-c.c
- lib/logsrv/log_server.proto
- lib/util/host_port.c
- lib/util/regress/host_port/host_port_test.c
- logsrvd/logsrv_util.h
- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
- logsrvd/logsrvd_conf.c
- logsrvd/sendlog.c
- plugins/sudoers/def_data.c
- plugins/sudoers/def_data.h
- plugins/sudoers/def_data.in
- plugins/sudoers/defaults.c
- plugins/sudoers/iolog.c
- plugins/sudoers/iolog_client.c
- plugins/sudoers/iolog_plugin.h
- plugins/sudoers/policy.c
For TLS connections we now do the TLS handshake immediately before the ServerHello message.  This lets the client receive an alert from the server is there is a handshake error after the TLS handshake has succeeded.  It also means that the contents of the ServerHello message are protected from a man-in-the-middle attack.  Non-TLS connections are now on port 30343 and the server listens on both 30343 and 30344 (TLS) by default.
> Use port 30343 for plaintext and port 30344 for TLS.

- logsrvd/logsrvd.c
- logsrvd/logsrvd.h
This fixes reject events as well as accept events without the expect_iobufs flag set.
> Fix handling of connections without associated I/O logs.

- include/sudo_debug.h
`mode_t` and `id_t` are used in `sudo_debug.h`, but are undefined if building with
musl libc. Per the [<sys/types.h> spec] it seems it should be included.
[<sys/types.h> spec]: https://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/types.h.html
> Fix includes when building with musl

- configure
- m4/sudo.m4
runstatedir was added in yet-to-be released autoconf 2.70. Some distros are shipping this addition in their autoconf packages, but others, such as Fedora, are not. This causes the rundir variable to be set incorrectly if the configure script is regenerated with an unpatched autoconf since the runstatedir variable set is deleted after regeneration. This change works around that problem by checking that runstatedir is non-empty before potentially using it to set the rundir variable
> configure: Fix runstatedir handling for distros that do not support it

- lib/eventlog/Makefile.in
Since version 1.9.4 and https://github.com/sudo-project/sudo/commit/bd1ca79cca827a92e904f022e49df121931d4ff5, when closefrom is not available, libsudo_eventlog.a depends on libsudo_util.a. So reflect this dependency in the libtool file to avoid the following static build failure of logsrvd:
```
/bin/bash ../libtool --tag=disable-static --mode=link /home/buildroot/autobuild/instance-1/output-1/host/bin/powerpc-linux-gcc -o sudo_logsrvd logsrv_util.o iolog_writer.o logsrvd.o logsrvd_conf.o -static -Wl,--enable-new-dtags -Wl,-z,relro    ../lib/iolog/libsudo_iolog.la ../lib/eventlog/libsudo_eventlog.la ../lib/logsrv/liblogsrv.la
/bin/bash ../libtool --tag=disable-static --mode=link /home/buildroot/autobuild/instance-1/output-1/host/bin/powerpc-linux-gcc -o sudo_sendlog logsrv_util.o sendlog.o …
```
> lib/eventlog/Makefile.in: fix static build without closefrom

- plugins/sudoers/auth/pam.c
If a PAM module wants to authenticate user using GSSAPI, the authentication
is broken if non-default ccache name is used in KRB5CCNAME environment
variable.
One way to mitigate this would be to add this to env_keep, but this also
makes the variable available in the executed command which may not
be always desirable.
This patch sets KRB5CCNAME for pam_authenticate only, if it is available
and not yet set.
---
An example of such module can be pam_sss_gss from the SSSD project.
https://github.com/SSSD/sssd/blob/master/src/sss_client/pam_sss_gss.c
https://github.com/SSSD/sssd/blob/master/src/man/pam_sss_gss.8.xml
> pam: pass KRB5CCNAME to pam_authenticate environment if available

- doc/sudo.man.in
- doc/sudo.mdoc.in
This PR fixes a tiny typo I spotted in the manpage for `sudo`, a missing `t` on the end of `prompt` in the `-B` section. Not really important, but may as well be fixed.
> Fix a tiny typo in the Sudo manpage

- src/selinux.c
Libselinux depricated the type few months ago:
https://github.com/SELinuxProject/selinux/commit/7a124ca2758136f49cc38efc26fb1a2d385ecfd9
Otherwise there are warnings during the build:
```
./selinux.c:61:5: warning: 'security_context_t' is deprecated [-Wdeprecated-declarations]
61 |     security_context_t old_context;
|     ^~~~~~~~~~~~~~~~~~
./selinux.c:62:5: warning: 'security_context_t' is deprecated [-Wdeprecated-declarations]
62 |     security_context_t new_context;
|     ^~~~~~~~~~~~~~~~~~
./selinux.c:63:5: warning: 'security_context_t' is deprecated [-Wdeprecated-declarations]
63 |     security_context_t tty_con_raw;
|     ^~~~~~~~~~~~~~~~~~
./selinux.c:64:5: warning: 'security_context_t' is deprecated [-Wdeprecated-declarations]
64 |     security_context_t new_tty_con_raw;
| …
```
> Removed depricated security_context_t

- src/utmp.c
When writing to utmp sudo_pututline() finds a suitable place to write the new utmp entry but does so after the current file position. sudo_getutline() will advance the file position while it's searching for the matching entry. In some cases there might be a pty but no matching entry for it in utmp i.e. `screen -ln`. This will advance the file offset to the end of the file and sudo_pututline() will just extend utmp and append an entry. For workloads that frequently call sudo this can lead to unbounded growth and substantial latency for anything that has to search the massive utmp file. Calling setutxent() again while it still has a fd open will seek to the beginning of the file and reuse a previous matching entry. This can be non-trivial to reproduce but looking at the output of utmpdump …
> Fix utmp resource leak

- lib/util/Makefile.in
When cross-build support was added for mkig{name,list} was added, the
CFLAGS and CPPFLAGS should have been updated to the HOSTCFLAGS/HOSTCPPFLAGS
vars.
In a cross-build scenario, some of these flags don't match what the
compiler can understand (because they may be architecture specific) and
may fail the build.
Using the HOSTCFLAGS/HOSTCPPFLAGS works and builds successfully.
Also the output binary works on the target.
This is in continuation of
- https://github.com/sudo-project/sudo/pull/104
- https://github.com/sudo-project/sudo/pull/109
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>
> lib: util: Makefile.in: use host CFLAGS and CPPFLAGS for mksig{name,list}

- plugins/sudoers/sudoers.in
When only the user (ALL) is specified explicitly, and the group is implied, only sudo -u works. Specifying both the user and group, like (ALL:ALL), is required to:
1) Use sudo -g by itself (with no -u user)
2) Use sudo -u and -g together, with a -g group that is different from the -u user's primary group
> Allow sudo -g anyone and sudo -u anyone -g anytwo

- plugins/sudoers/policy.c
When no default timeout is set in /etc/sudoers, the def_command_timeout variable
is set to 0 and then in sudoers_policy_store_result is considered to be smaller than
whatever the user specified on the command line (via the -T option), even though 0
in this case should be considered infinity.
I reproduced with sudo 1.9.5, but current version should be affected too. Without this patch:
```
germ61:~ # grep timeout /etc/sudoers
Defaults user_command_timeouts
germ61:~ # time sudo -T 5 sleep 10
real	0m10.109s
user	0m0.033s
sys	0m0.073s
```
With the patch:
```
germ61:~ # grep timeout /etc/sudoers
Defaults user_command_timeouts
germ61:~ # time sudo -T 5 sleep 10
Hangup
real	0m5.087s
user	0m0.026s
sys	0m0.062s
```
> Do not unset user timeout when no default timeout is set.

- plugins/sudoers/auth/kerb5.c
If sudo is using the Kerberos sudoers-auth plugin, it overwrites a custom prompt set with `-p`.  This patch changes the behavior so the custom prompt is not overwritten.
Thanks to @thend20 for testing this patch.
> If we're using Kerberos, don't overwrite a custom prompt

- plugins/sudoers/sudoers.in
Fix a typo in the sudoers comment about `maxseq` param.
Introduced by 906eb19ece47023c659b4b3db2e7a6bb57dff0d9 in 1.9.11.
> Fix typo in sudoers comment

- src/exec_ptrace.h
AArch64 already had an existing "user_pt_regs" struct and didn't need a
struct alias before the renaming to "sudo_pt_regs". Make the code build
again by adding the now missing alias.
Fixes: 2eb8ff17
> exec_ptrace: fix missing sudo_pt_regs on aarch64

- plugins/sudoers/visudo.c
Neovim [supports it](https://neovim.io/doc/user/starting.html#-+).
> visudo.c: add nvim (Neovim) to lineno_editor list

- lib/util/sha2.c
Resolves an issue where certain message sizes result in an incorrect
checksum. Specifically, when:
(n*8) mod 1024 == 896
where n is the file size in bytes.
> Fix incorrect SHA384/512 digest calculation.

- plugins/sudoers/env.c
Qt needs `XDG_CURRENT_DESKTOP` to be set to determine the correct theme.
Since `DISPLAY` and `XAUTHORITY` are already in the default table of variables to preserve in the environment, just add `XDG_CURRENT_DESKTOP` to it.
Bug: https://launchpad.net/bugs/1958055
> Add XDG_CURRENT_DESKTOP to initial_keepenv_table

- plugins/sudoers/parse_ldif.c
For the following piece of code:
https://github.com/sudo-project/sudo/blob/9f948224acb911cbec1ed9041887c1fe62c59877/plugins/sudoers/parse_ldif.c#L689-L698
`sudo` appears to be reading until it encounters a comma character or a null byte. However, in the case where it encounters something line similar to `dn:cn=sudo\`, sudo will keep reading beyond the null byte into unitialized memory/neighbouring buffers. This could lead to unexpected behaviour especially if the adjacent buffer contains the same string as that defined in `sudoers_base`.
> [cvtsudoers]: Prevent sudo from reading into undefined memory

- plugins/sudoers/auth/pam.c
A memory leak may occur in the exception branch. #199
> Fix memory leak of pass in converse().

- lib/util/mmap_alloc.c
https://github.com/sudo-project/sudo/issues/204
> sudo_mmap_strdup_v1: Fix potential NULL pointer deref

- lib/util/snprintf.c
I don't think this particular code-block is currently reachable since I am not able to get a reproducible crash for this.
However, it seems like the following peice of code at:
https://github.com/sudo-project/sudo/blob/e707ffe58b3ccfe5c72f54c38eac1d7069d5021e/lib/util/snprintf.c#L1155-L1162
allows the program to read beyond a null-byte in a string into undefined memory. 
The for loop in the code will terminate if it reaches a null-byte or a '%' character. However, immediately after, the character is unconditionally being skipped and the program keeps on executing regardless of whether or not it encountered a null-byte.
> [snprintf] Check for '\0' to prevent undef memory read

- plugins/sudoers/env.c
When the following line is encountered in a `/etc/environment` style file:
```
ENV_NAME='
```
the following code:
https://github.com/sudo-project/sudo/blob/8b5037a2117a0f03c34008514469bac22ff99490/plugins/sudoers/env.c#L1281-L1285
allows `val_len` to be set to -1 (since it assumes a closing end quote which will not be present).
Currently the underflowed value does not cause issues due to the surrounding code adding 1 to `val_len` whenever it is used, however it could become a issue later on if the code is moved around.
> Prevent integer underflow due to environment variable

- etc/sudo.pp
Debian >= 10 uses AppArmor by default instead of SELinux, so SELinux-related sudo features are typically going to be unusable in Debian installs. This changes the dependency on libselinux1 to be a dependency on libapparmor1 for .deb packages built with `make package`.
> Replace the Debian libselinux1 dependency with libapparmor1

- m4/openssl.m4
Do not use `AX_APPEND_FLAG` as it will break static builds by removing duplicates such as `-lz` or `-latomic` which are needed by `-lssl` and `-lcrypto`. This will fix the following build failure with sparc which needs `-latomic`:
```
Checking for X509_STORE_CTX_get0_cert
configure:21215: /home/thomas/autobuild/instance-3/output-1/host/bin/sparc-buildroot-linux-uclibc-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0  -static -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DZLIB_CONST  -static conftest.c   -L/home/thomas/autobuild/instance-3/output-1/host/bin/../sparc-buildroot-linux-uclibc/sysroot/usr/lib -lssl -lz -pthread -latomic -lcrypto >&5
/home/thomas/autobuild/instance-3/output-1/host/lib/gcc/sparc-buildroot-linux-uclibc/10 …
```
> configure.ac: fix openssl static build

- lib/eventlog/parse_json.c
- lib/util/sudo_debug.c
- plugins/sudoers/fmtsudoers.c
It does not hurt when the functions that take the variable later on as an argument also expect them to be size_t.
> Prefer size_t over int, as casting can take extra instructions

- plugins/sudoers/alias.c
Is it better to return a value of bool?
> correct the return value type of function alias_find_used

- include/sudo_event.h
- lib/util/event.c
- lib/util/rcstr.c
- plugins/sudoers/canon_path.c
- plugins/sudoers/ldap_conf.c
- plugins/sudoers/sudo_ldap_conf.h
Variable length arrays are supported by C99, but having it denoted as "1" confused the compiler and is not defined.
Note that because we don't get the inferred NULL terminator, we have to increase the malloc size by one.
> Do variable length arrays the C99 way

- plugins/sudoers/match_command.c
Because the return value of the is_script function is bool type, so change 'debug_return_int(ret)' to 'debug_return_bool(ret)'
> Modify the is_script function for match_command.c

- plugins/sudoers/policy.c
The lack of setting to NULL is a holdover from when command_info was a local variable and not a global one. However, we given how other global variables are set to NULL, it is best that we do the same here to avoid potential issues should sudoers_policy_store_result be called again after the first time failed, otherwise we could get a double-free.
> Set command_info to NULL once it is freed

- logsrvd/logsrvd.c
1 is for failure, 0 is for no failure, and this does not look like a failure.
> We should be returning 0, not 1, when logservd finishes without errors

- lib/util/parseln.c
- lib/util/roundup.c
- logsrvd/logsrvd_journal.c
We should be checking for integer overflow, rather than checking if size is 0.
Additionally, we should set errno to ENOMEM when this overflow happens.
Finally, the most efficient implementation of the round-up-to-2 algorithm involves the clz intrinsic.
> Fix fuzzing errors

- lib/util/roundup.c
size_t is an unsigned int on 32-bit platforms, not an unsigned long.
> Use U, not UL, for 32-bit platforms

- plugins/sudoers/visudo.c
Orbiton is an editor that is packaged for these systems:
| As **orbiton**                                                                                                                    | As **o-editor**                                                                                                                     |
|--------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| [![Packaging status](https://repology.org/badge/vertical-allrepos/orbiton.svg)](https://repology.org/project/orbiton/versions) | [![Packaging status](https://repology.org/badge/vertical-allrepos/o-editor.svg)](h …
> Add Orbiton to the list of editors that supports "+lineno"

- plugins/sudoers/auth/kerb5.c
Commit 244017495421 added ctx variable to log_warningx() call but that variable was not declared in that context, breaking the build.
This change fixes issue #320
> Add missing sudoers_context to verify_krb_v5_tgt()

- lib/util/glob.c
- plugins/sudoers/tsdump.c
putchar is easier to understand than fputc and printf and does less work than those two do.
> Prefer putchar over fputc where possible

- src/exec_ptrace.c
Commit 32f4b98f6b4a (sudo frontend: silence most -Wconversion warnings.) broke the build on C libraries that miss process_vm_readv(), like uClibc-ng.
Indeed, the ssize_t nwritten is declared guarded by HAVE_PROCESS_VM_READV, but is then re-assigned and used a few lines below, outside any guard.
Fix that by always declaring the object, as it is always needed.
> src/exec_ptrace: fix build without precess_vm_readv()

- lib/util/Makefile.in
Currently, we generate the signal list and names by running cpp on our header, and piping the result into sed.
However, when cpp fails [0], we do not catch that failure, as the error code of the LHS of a pipe is lost, with the pipe returning the RHS-most return code.
Fix that by introducing two new intermediate rules, each to generate the preprocessed .i files, and use those as dependencies and input to the rule that generates the headers. Those two .i files will be cleaned up by the existing *.i glob.
[0] a failure happens on recent hosts, due to inconsistency with time64_t and large-file support (lines elided and wrapped for readability):
/usr/bin/cpp [...] ./sys_signame.h \
| /usr/bin/sed -e '1,/^int sudo_end_of_headers;/d' -e '/^#/d' > mksigname.h
In file included from …
> lib/utils: detect failure to generate signals list and names

- m4/openssl.m4
Do not append `-I/usr/include/wolfssl` when cross-compiling
> m4/openssl.m4: fix cross-compilation with wolfssl

- logsrvd/logsrvd.c
- logsrvd/tls_client.c
- plugins/sudoers/log_client.c
I have accidentally generated wrong certificate for the sudo_logsrvd client for TLS communication (it was for a server and not a client), and felt it a bit hard to debug what the problem could be. Ended up adding these log messages, I think they could be useful.
Example message looks like this:
May 15 12:13:15.611 sudo_logsrvd[23971] TLS verification failed for cert '/C=US/ST=Utah/O=sudo/OU=sudo Audit Server/CN=QPM': '26:unsupported certificate purpose' @ verify_peer_identity() ./logsrvd.c:1271
> logsrvd,plugins/sudoers: add debug log on TLS verification error

- include/sudo_iolog.h
- plugins/sudoers/iolog_path_escapes.c
This matches the same functions in check_iolog_path.
> Restrict-qualify iolog_path_escapes like we do with check_iolog_path

- include/sudo_compat.h
- lib/util/fstatat.c
- lib/util/gmtime_r.c
- lib/util/inet_pton.c
- lib/util/localtime_r.c
- lib/util/utimens.c
All function definitions taken from Linux and POSIX.
> Use the full definition of the emulated function that is missing

- plugins/sudoers/parse.h
Definition restrict qualifies but not declaration in header.
> Restrict-qualify dst in base64_decode

- src/load_plugins.c
sudo_qualify_plugin was probably meant instead
> Replace sudo_stat_plugin with sudo_qualify_plugin, as sudo_stat_plugin does not exist

- include/sudo_util.h
- lib/util/hexchar.c
sudo_hexchar_v1 requires an array of at least size-2, and is not aliased.
> Restrict-qualify sudo_hexchar_v1

- docs/sudoers.man.in
- docs/sudoers.mdoc.in
The `sudoers(5)` man page entry for the `pam_silent` Defaults option incorrectly says that "This settings is only supported by version 1.**8**.16 or higher." (emphasis mine). This is incorrect, since the setting was added in 1.**9**.16.
This PR fixes this simple typo.
> Fix version typo for pam_silent option in sudoers man page

- plugins/sudoers/sudoers.in
This PR adds a commented `Defaults !pam_silent` and an explanatory sentence to the default `sudoers` file.
Since it is possible that some users might be running into `pam_faillock` leading to inexplicably failing login attemps with no explanatory output (#216), making this option easily accessible could help these users fix their issue or rule out one problem more quickly without having to dig into the sudoers man page.
> Add pam_silent setting to sudoers example config

- configure.ac
- plugins/sudoers/sudoers.in
As someone who packages `sudo` for a distribution, we received a number of reports from people surprised by the change in behaviour when we updated to sudo 1.9.16 within our stable release train. We'd like the option to preserve the previous behaviour of shipping `/etc/sudoers` with the `secure_path` option commented out for now.
This PR adds `--secure-path-value=no` to achieve that.
The interaction of the secure path configure parameters is a bit overloaded in that the single `secure_path` variable is updated by both `--with-secure-path` and `--with-secure-path-value`, the difference being whether it is just substituted into the installed `etc/sudoers` file or also built into the plugin as the default path. I didn't opt to change anything here to preserve backwards compabitility, but I …
> Allow --secure-path-value=no

- plugins/sudoers/auth/pam.c
PAM modules can change the user during their execution, in such case, sudo would still use the user that has been provided giving potentially access to another user with the credentials of another one.
So prevent this to happen, by ensuring that the final PAM user is matching the one which started the transaction.
Similar to https://github.com/util-linux/util-linux/pull/3206
> plugins/pam: Check the user didn't change during PAM transaction

- plugins/sudoers/sudoers.in
A line in the sudoers file contains a tab where a space seems to be more appropriate. 
Since the tab in question is on col 8 it looks a lot like a space in many editors, but is revealed to be a tab if one were to change its position (ie. by uncommenting the line). Tabs in similar places were replaced with spaces in commit 76ce690, so this change would make the formatting of the sudoers file a bit more consistent.
> Replace tab with space in sudoers file

- src/ttyname.c
The ppid field in /proc/self/stat is the fourth and not the third. The latter is the process state (S, R, etc.).
> Fix getting ppid in get_process_ttyname for Linux.

- src/exec_pty.c
Hey!
It's just a small typo I noticed while reviewing the source code.
Thanks :)
> Fix a typo in the description of exec_pty()

- docs/cvtsudoers.mdoc.in
- docs/sudo.conf.mdoc.in
- docs/sudo.mdoc.in
- docs/sudo_logsrv.proto.mdoc.in
- docs/sudo_logsrvd.conf.mdoc.in
- docs/sudo_logsrvd.mdoc.in
- docs/sudo_plugin.mdoc.in
- docs/sudo_plugin_python.mdoc.in
- docs/sudo_sendlog.mdoc.in
- docs/sudoers.ldap.mdoc.in
- docs/sudoers.mdoc.in
- docs/sudoers_timestamp.mdoc.in
- docs/sudoreplay.mdoc.in
- docs/visudo.mdoc.in
- Fix repeated grammar mistake: "Please not report" → "Please do not report".
- Correct phrasing around "fully qualified path" for consistency.
- Fix duplicate word: "The the" → "The" in sudo_logsrv.proto.
- Update Protocol Buffers URL to the updated canonical URL.
- Minor rewordings in sudo.conf examples to improve clarity of policy checks.
> Fix minor grammar errors and outdated URLs in man pages

- lib/iolog/iolog_write.c
- plugins/python/regress/iohelpers.c
- plugins/sudoers/sudo_printf.c
- src/conversation.c
fwrite is not the same as write; you have to explicitly compare against the length to detect errors, and sometimes number of items is mistaken for length.
> Properly check against errors against fwrite

- m4/hardening.m4
Before, Intel CET was enabled for both 32-bit and 64-bit targets.
However, this made sudo incompatible with semi-i686 non-Intel and non-AMD processors, such as DM&P Vortex86 processors that are still in production, and legacy VIA/Geode processors. On those, generated ENDBR32 instructions are parsed as invalid opcodes, crashing sudo with a SIGILL:
- https://lists.debian.org/debian-devel/2023/10/msg00118.html
- https://bugs.gentoo.org/862201
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264497
Even for modern processors that support it, enabling it does not enhance security as no kernel in 32-bit mode supports Intel CET (neither Linux nor FreeBSD nor OpenBSD), so enabling it only increases the binary size at best and prevents entirely from running at worst.
This commit changes the …
> Enable Intel CET on x86-64 only
